sudo: false

language: node_js

branches:
  only:
    - master

services:
  - mongodb

node_js:
  - "4.0"
  - "0.12"
  - "0.11"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - npm install
  - npm install jshint mocha

script:
  - npm run lint
  - travis_wait travis_retry istanbul cover -x **/lib/** ./node_modules/mocha/bin/_mocha test/marketeer.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
