sudo: false

language: node_js

branches:
  only:
    - master

services:
  - mongodb

node_js:
  - "0.12"
  - "0.11"

before_script:
  - npm install
  - npm install jshint mocha

script:
  - npm run lint
  - travis_wait travis_retry istanbul cover -x **/lib/** ./node_modules/mocha/bin/_mocha test/marketeer.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
